### ISSUE TITLE
Logo Design: Exploration-game

### ISSUE THREAD

**Issue by baranpirincal** [joaquinariasgomez/Exploration-game#1]
Hello!

 I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by joaquinariasgomez** [comment]
Hi!

Of course, I would be happy to receive your work.

The main idea of this project is to make a survival exploration game. So, since the astronauts will be the protagonists and there will be many dangers on the planet to explore, the logo could contain an astronaut, an alien/multiple aliens (if I like the alien concept I could make the model for the game and quote you :)) and the planet.

If you have any questions about the temathic of the game or some other subject of the game, you are welcome to ask me.

Greetings.

**Comment by baranpirincal** [comment]
@empiremay

Hey again! 

Here the first experiment:

- Astronout
- Multiple Aliens
- Planet 

![exploration-game](https://user-images.githubusercontent.com/37786733/41504387-3d6b6dba-71f6-11e8-9653-853e3b2e4313.jpg)

**Comment by baranpirincal** [comment]
![explore-color variations](https://user-images.githubusercontent.com/37786733/41504730-09edd10c-7201-11e8-81a9-01144057a70c.jpg)

**Comment by baranpirincal** [comment]
I will work more to combine them

**Comment by joaquinariasgomez** [comment]
Hi!

I like the astronaut design, but i would like to see more of the planet in the logo. Could you move the astronaut logo to the right and remove one alien?

I like a lot the multicolor planet (violet and red/pink).

I would like to see the alien hidden among several rocks on the left of the planet.

Great work!

**Comment by baranpirincal** [comment]
@empiremay 

Hey, thanks!

I made different variations, whichever you choose we can work on that :)

![lastly expoloration](https://user-images.githubusercontent.com/37786733/41534388-1cb666f8-7307-11e8-9264-ee0ed985d90e.jpg)

**Comment by joaquinariasgomez** [comment]
Wow! They're awesome.

I like a lot this one:

![image](https://user-images.githubusercontent.com/28860690/41535354-4a0c8312-7302-11e8-9dd1-a6eb93250ac6.png)

**Comment by baranpirincal** [comment]
@empiremay 

Nice!

I will do some arrangements, after that I will upload the files in .SVG , .PNG , .JPG  format. Is it enough for you?

**Comment by joaquinariasgomez** [comment]
Yes, that's fine.

**Comment by baranpirincal** [comment]
I made some arrangements about alignment.

Which one do you prefer? (only differences on hands of alien)

![lastlastlastl](https://user-images.githubusercontent.com/37786733/41605231-ac636534-73e9-11e8-9212-1b887511a0fd.jpg)

**Comment by joaquinariasgomez** [comment]
Hi again!

I prefer the second :)

**Comment by baranpirincal** [comment]
Good luck with that! :)

**Comment by baranpirincal** [comment]
![exploration-game-cover](https://user-images.githubusercontent.com/37786733/41710606-c2cf9a84-754e-11e8-9623-be45a7e77fba.jpg)

**Comment by joaquinariasgomez** [comment]
Hi again!

Can I get the .PNG files of the black and white version?

Greetings.

**Comment by baranpirincal** [comment]
@empiremay

All necessary source files here: 

https://drive.google.com/folderview?id=17lY3CEfFTR8-giZwKvFwNKEG9WgRZ6oR

Best Regards

Baran Pirinçal
